name: Build/Test

on:
  push:
    branches: "main"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure CMake
      run:  cmake -B '${{github.workspace}}/build' -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run:  cmake --build '${{github.workspace}}/build' --config Release

    - name: Run Integration Tests
      working-directory: ${{github.workspace}}/build
      run:  ctest -C Release --output-on-failure -LE "stress"

    - name: Run Stress Tests
      if: matrix.os == 'ubuntu-latest'
      working-directory: ${{github.workspace}}/build
      env:
          ASAN_OPTIONS: "detect_leaks=1:strict_string_checks=1"
      run: ctest -C Release --output-on-failure -L "stress"
